import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * 根布局组件. 此组件用作应用的根布局, 包含基本的HTML和BODY结构.
 * 它接受一个子元素，该子元素可以是任何React组件, 并将其作为页面的内容区域进行渲染.
 * 
 * @param {Readonly<{ children: React.ReactNode }>} props - 组件的props.
 * @param {React.ReactNode} props.children - 要渲染在页面内容区域的子元素.
 * @returns {JSX.Element} 一个包含基本HTML结构和子元素的JSX元素.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
